# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/flayers',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/flayers',
                'lib_path': 'flayers'},
  'syms': { 'flayers.layers': { 'flayers.layers.cast_all': ('layers.html#cast_all', 'flayers/layers.py'),
                                'flayers.layers.create_gabor_rot_tf': ('layers.html#create_gabor_rot_tf', 'flayers/layers.py'),
                                'flayers.layers.create_multiple_different_rot_gabor_tf': ( 'layers.html#create_multiple_different_rot_gabor_tf',
                                                                                           'flayers/layers.py'),
                                'flayers.layers.create_multiple_random_rot_gabor_tf': ( 'layers.html#create_multiple_random_rot_gabor_tf',
                                                                                        'flayers/layers.py'),
                                'flayers.layers.gabor_2d_tf': ('layers.html#gabor_2d_tf', 'flayers/layers.py')}}}