# AUTOGENERATED! DO NOT EDIT! File to edit: ../Notebooks/02_constraints.ipynb.

# %% auto 0
__all__ = ['Positive']

# %% ../Notebooks/02_constraints.ipynb 2
import tensorflow as tf
from tensorflow.keras.constraints import Constraint

# %% ../Notebooks/02_constraints.ipynb 3
class Positive(Constraint):
    """Constraint to force positive weights in a layer."""

    def __call__(self, w):
        return w * tf.cast(tf.math.greater_equal(w, 0. + 1e-5), w.dtype)
